// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtSY1sey-cYhnPcbiyd7bUuVGU27XAm7k',
    appId: '1:1027194375005:web:0df2e622330ff3c2baf6b4',
    messagingSenderId: '1027194375005',
    projectId: 'cmbq153vorkf7m3umymp5sxm59xoc8',
    authDomain: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebaseapp.com',
    storageBucket: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5mHtiKLmm84pdvKG_cjpnUk2u9uNYZ7I',
    appId: '1:1027194375005:android:a14edbd36e24a4a3baf6b4',
    messagingSenderId: '1027194375005',
    projectId: 'cmbq153vorkf7m3umymp5sxm59xoc8',
    storageBucket: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0_ZuvJ3N_3fw5SMV7Lhx_vTYSA32G78',
    appId: '1:1027194375005:ios:8ce8032926708babbaf6b4',
    messagingSenderId: '1027194375005',
    projectId: 'cmbq153vorkf7m3umymp5sxm59xoc8',
    storageBucket: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebasestorage.app',
    iosBundleId: 'goncalves.erick.appFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0_ZuvJ3N_3fw5SMV7Lhx_vTYSA32G78',
    appId: '1:1027194375005:ios:8ce8032926708babbaf6b4',
    messagingSenderId: '1027194375005',
    projectId: 'cmbq153vorkf7m3umymp5sxm59xoc8',
    storageBucket: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebasestorage.app',
    iosBundleId: 'goncalves.erick.appFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtSY1sey-cYhnPcbiyd7bUuVGU27XAm7k',
    appId: '1:1027194375005:web:4e920293b958654ebaf6b4',
    messagingSenderId: '1027194375005',
    projectId: 'cmbq153vorkf7m3umymp5sxm59xoc8',
    authDomain: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebaseapp.com',
    storageBucket: 'cmbq153vorkf7m3umymp5sxm59xoc8.firebasestorage.app',
  );
}
